apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    app: immich
namespace: immich
resources:
  - namespace.yaml
  - immich-env-configmap.yaml
  - immich-deployment.yaml
